# 2024-10-11-TIL

안녕하세요.

오늘은 Swift에서 에러 처리에 대해서 알아보도록 하겠습니다.

주로 예시 코드로 알아보도록 할게요.

## 에러처리(Error Handling)

### 에러 종류

1. 컴파일 타임 에러
   - Swift 문법과 관련된 에러(컴파일러가 미리 알고 수정해야한다고 알려줍니다.)
2. 런타임 에러
   - 프로그램이 실행되는 동안 발생합니다.
   - 크래시(앱이 강제로 종료됩니다.)
   - 발생 가능한 에러를 미리 처리해두면, 강제 종료되지 않습니다.(개발자가 처리해야만 하는 에러)

<br/>

### 에러 처리의 과정(3단계)

```swift
// 1) 에러 정의 (어떤 에러가 발생할지 경우를 미리 정의)
enum HeightError: Error { // 에러 프로토콜 채택 (약속)
    case maxHeight
    case minHeight
}

// 2) 에러가 발생할 수 있는 함수에 대한 정의
// 에러 발생가능한 상황에 throw 키워드로 에러를 던질(throwing)수 있도록 정의
func checkingHeight(height: Int) throws -> Bool { // (에러를 던질 수 있는 함수 타입이다.)
    if height > 190 {
        throw HeightError.maxHeight
    } else if height < 130 {
        throw HeightError.minHeight
    } else {
        if height >= 160 {
            return true
        } else {
            return false
        }
    }
}

// 3) 에러가 발생할 수 있는 함수의 처리(함수의 실행) ---> 기존과 조금 다르다. (try와 do-catch 문으로 처리)
// 정식적인 처리방법: do-catch 블럭에서 처리(조금 간편한 방식도 존재)
do {
    let isChecked = try checkingHeight(height: 200)
    print("놀이기구 타는 것 가능: \(isChecked)")
} catch {
    print("놀이기구 타는 것 불가능")
}
```

<br/>

### 에러를 처리하는 방법 

> try / try? / try!

```swift
/**===========================================
 1) 에러 정식 처리 방법
 - 모든 에러발생의 예외적인 경우를 디테일하게 처리 가능
 ============================================**/
do {
    let isChecked = try checkingHeight(height: 200)
    
    if isChecked {
        print("청룡열차 가능")
    } else {
        print("후룸라이드 가능")
    }
} catch {
    print("놀이기구 타는 것 불가능")
}

/**===========================================
 2) try? (옵셔널 트라이) ===> 옵셔널 타입으로 리턴
 
 (1) 정상적인 경우 ==> (정상)리턴타입으로 리턴
 (2) 에러가 발생하면 ==> nil 리턴
 ============================================**/
let isChecked = try? checkingHeight(height: 200)      // Bool? --> 당연히, 옵셔널 타입을 벗겨서 사용해야함

/**===========================================
 3) try! (Forced 트라이) ===> 에러가 날 수 없는 경우에만 사용 가능
 
 (1) 정상적인 경우 ==> (정상)리턴타입으로 리턴
 (2) 에러가 발생하면 ==> 런타임에러
 ============================================**/
let isChecked2: Bool = try! checkingHeight(height: 150)      // Bool --> 에러가 발생할 수 없다고 확신이 있는 경우만 사용해야 함.
```

<br/>

### catch 블럭 처리 방법

```swift
// catch블럭은 do블럭에서 발생한 에러만을 처리하는 블럭
// 모든 에러를 반드시 처리해야만 함 (글로벌 스코프에서는 모든 에러를 처리하지 않아도 컴파일 에러발생하지 않음)

// 패턴이 있는 경우(모든 에러를 각각 따로 처리 해야함)
do {
    let isChecked = try checkingHeight(height: 100)
    print("놀이기구 타는 것 가능: \(isChecked)")
} catch HeightError.maxHeight  {    // where절을 추가해서, 매칭시킬 에러패턴에 조건을 추가할 수 있음
    print("키가 커서 놀이기구 타는 것 불가능")
} catch HeightError.minHeight {      // 생략가능
    print("키가 작아서 놀이기구 타는 것 불가능")
}

// catch 패턴이 없이 처리도 가능
do {
    let isChecked = try checkingHeight(height: 100)
    print("놀이기구 타는 것 가능: \(isChecked)")
} catch {    // error 상수를 제공 (모든 에러가 넘어옴)
    print(error.localizedDescription)
    
    if let error = error as? HeightError {    // 실제 우리가 정의한 구체적인 에러 타입이 아니고, 에러 타입(프로토콜)이 넘어올 뿐
        switch error {
        case .maxHeight:
            print("키가 커서 놀이기구 타는 것 불가능")
        case .minHeight:
            print("키가 작아서 놀이기구 타는 것 불가능")
        }
    }
}

// Swift 5.3이후 catch블럭의 처리
do {
    let isChecked = try checkingHeight(height: 100)
    print("놀이기구 타는 것 가능: \(isChecked)")
} catch HeightError.maxHeight, HeightError.minHeight {   // 케이스 나열도 가능해짐
    print("놀이기구 타는 것 불가능")
}
```

<br/>

### 에러를 던지는 함수를 처리하는 함수

#### 에러 정의

```swift
// 에러정의
enum SomeError: Error {
    case aError
}

// 에러를 던지는 함수 정의 (무조건 에러를 던진다고 가정)
func throwingFunc() throws {
    throw SomeError.aError
}

// 에러의 처리
do {
    try throwingFunc()
} catch {
    print(error)
}
```

#### 일반적인 함수로 처리

```swift
// 함수 내부에서 do-catch문으로 에러를 처리
// 즉, 발생한 에러를 catch블럭에서 받아서 알맞은 처리
func handleError() {
    do {
        try throwingFunc()
    } catch {
        print(error)
    }
}

handleError()
```

#### 1- throwing함수로 에러 다시 던지기

```swift
/**====================================================
 - 함수 내에서 에러를 직접처리하지 못하는 경우, 에러를 다시 던질 수 있음
 ====================================================**/
func handleError1() throws {
    //do {
    try throwingFunc()
    //}                     // catch블럭이 없어도 에러를 밖으로 던질 수 있음 ⭐️
}

do {
    try handleError1()   // 에러를 받아서 처리 가능
} catch {
    print(error)
}
```

#### 2 - rethrowing함수로 에러 다시 던지기(rethrows 키워드)

```swift
/**================================================================
 - 에러를 던지는 throwing함수를 파라미터로 받는 경우, 내부에서 다시 에러를 던지기 가능
 - rethrows키워드 필요 (Rethrowing메서드)
 ==================================================================**/

// 다시 에러를 던지는 함수(방법1)
func someFunction1(callback: () throws -> Void) rethrows {
    try callback()             // 에러를 다시 던짐(직접 던지지 못함)
    // throw (X)
}

// 다시 에러를 던지는 함수(방법2) - 에러변환
func someFunction2(callback: () throws -> Void) rethrows {
    enum ChangedError: Error {
        case cError
    }
    
    do {
        try callback()
    } catch {   // catch구문에서는 throw (O)
        throw ChangedError.cError    // 에러를 변환해서 다시 던짐
    }
}

// 실제 에러를 다시던지는(rethrowing)함수를 처리하는 부분
do {
    try someFunction1(callback: throwingFunc)
} catch {
    print(error)
}

do {
    try someFunction2(callback: throwingFunc)
} catch {
    print(error)
}
```

<br/>

### Defer문

- defer문은 **코드의 실행을 스코프가 종료되는 시점으로 연기시키는 문법**입니다/
- 일반적인 사용은, 어떤 동작의 마무리 동작을 특정하기 위해서 사용 (정리의 개념)

```swift
func deferStatement1() {
    defer {
        print("나중에 실행하기")
    }   
    print("먼저 실행하기")
}
deferStatement1()
// 먼저 실행하기
// 나중에 실행하기

func deferStatement2() { 
    if true {
        print("먼저 실행하기")
        return
    }  
    defer {                   // 디퍼문이 호출되어야, 해당 디퍼문의 실행이 예약되는 개념
        print("나중에 실행하기")
    }
}
deferStatement2()
// 먼저 실행하기

// 등록한 역순으로 실행  ====> 일반적으로 하나의 디퍼문만 사용하는 것이 좋음
func deferStatement3() {
    defer {
        print(1)
    }
    defer {
        print(2)
    }
    defer  {
        print(3)
    }
}
deferStatement3()
// 3
// 2
// 1

// 어떻게 실행될까?
for i in 1...3 {
    defer { print ("Defer된 숫자?: \(i)") }
    print ("for문의 숫자: \(i)")
}
// for문의 숫자: 1
// Defer된 숫자?: 1
// for문의 숫자: 2
// Defer된 숫자?: 2
// for문의 숫자: 3
// Defer된 숫자?: 3
```

<br/>

<br/>

오늘 정리한 내용은 여기까지 입니다.

읽어주셔서 감사합니다.